influxdb:
  image: tutum/influxdb:latest
  container_name: influxdb
  ports:
   - "8083:8083"
   - "8086:8086"
  volumes:
   - ./influxdb:/data/db
  volume_driver: local
grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
  - "3000:3000"
  links:
  - influxdb 
